name: Vercel Deployment
description: Deploys to Vercel
inputs:
  target-env:
    description: 'The target environment (staging/production)'
    type: string
    required: true
  service:
    description: 'The service/app to deploy'
    type: string
    required: true
  is_forked:
    description: 'That PR is a fork (or not)'
    type: string
    required: false
    default: 'false'
secrets:
  # all vercel deployments
  NEXT_PUBLIC_BASE64_WEDLOCKS_PUBLIC_KEY:
    required: false
  NEXT_PUBLIC_STRIPE_KEY:
    required: false
  NEXT_PUBLIC_ETHPASS_KEY:
    required: false
env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
runs:
  using: 'composite'
  steps:
    - run: echo Deploying ${{ inputs.service }}.
      shell: bash
    - name: Deploy to Vercel
      shell: bash
      run: |
        # show args
        echo "${{ inputs.target-env }} ${{ inputs.service }} vercel (project-id: $VERCEL_PROJECT_ID) $GITHUB_SHA $GITHUB_REF_NAME ${{ inputs.is_forked  }}"
        # run command
        scripts/deploy.sh ${{ inputs.target-env }} ${{ inputs.service }} vercel "$GITHUB_SHA" "$GITHUB_REF_NAME" ${{ inputs.is_forked }}
