sudo: required

language: generic

services:
  - docker

before_install:
  - docker-compose -f docker/docker-compose.ci.yml build
  - docker-compose -f docker/docker-compose.ci.yml up --abort-on-container-exit
