checksumBehavior: update

nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: '${NPM_AUTH_TOKEN-fallback}'

npmPublishAccess: public

npmPublishRegistry: 'https://registry.npmjs.org/'

npmRegistryServer: 'https://registry.npmjs.org/'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: 'https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.2.4.cjs

packageExtensions:
  'eslint-config-next@*':
    dependencies:
      'next': '*'
