checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: "${NPM_AUTH_TOKEN-fallback}"

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org/"

npmRegistryServer: "https://registry.npmjs.org/"

# prevent caret from being added when using `yarn up`
defaultSemverRangePrefix: ""

packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
