export const FATAL_MISSING_PROVIDER = 'FATAL_MISSING_PROVIDER'
export const FATAL_WRONG_NETWORK = 'FATAL_WRONG_NETWORK'
export const FATAL_NO_USER_ACCOUNT = 'FATAL_NO_USER_ACCOUNT'
export const FATAL_NON_DEPLOYED_CONTRACT = 'FATAL_NON_DEPLOYED_CONTRACT'

export const MISSING_PROVIDER = 'MISSING_PROVIDER'
export const MISSING_TRANSACTION = 'MISSING_TRANSACTION'
export const FATAL_NOT_ENABLED_IN_PROVIDER = 'FATAL_NOT_ENABLED_IN_PROVIDER'
export const NON_DEPLOYED_CONTRACT = 'NON_DEPLOYED_CONTRACT'

export const FORM_LOCK_NAME_MISSING = 'FORM_LOCK_NAME_MISSING'
export const FORM_EXPIRATION_DURATION_INVALID =
  'FORM_EXPIRATION_DURATION_INVALID'
export const FORM_MAX_KEYS_INVALID = 'FORM_MAX_KEYS_INVALID'
export const FORM_KEY_PRICE_INVALID = 'FORM_KEY_PRICE_INVALID'

export const NO_USER_ACCOUNT = 'NO_USER_ACCOUNT'

// Transaction failures
export const FAILED_TO_CREATE_LOCK = 'FAILED_TO_CREATE_LOCK'
export const FAILED_TO_PURCHASE_KEY = 'FAILED_TO_PURCHASE_KEY'
export const FAILED_TO_UPDATE_KEY_PRICE = 'FAILED_TO_UPDATE_KEY_PRICE'
export const FAILED_TO_WITHDRAW_FROM_LOCK = 'FAILED_TO_WITHDRAW_FROM_LOCK'
