export const FATAL_MISSING_PROVIDER = 'FATAL_MISSING_PROVIDER'
export const FATAL_WRONG_NETWORK = 'FATAL_WRONG_NETWORK'
export const FATAL_NO_USER_ACCOUNT = 'FATAL_NO_USER_ACCOUNT'
export const FATAL_NON_DEPLOYED_CONTRACT = 'FATAL_NON_DEPLOYED_CONTRACT'

export const MISSING_PROVIDER = 'MISSING_PROVIDER'
export const MISSING_TRANSACTION = 'MISSING_TRANSACTION'
export const FATAL_NOT_ENABLED_IN_PROVIDER = 'FATAL_NOT_ENABLED_IN_PROVIDER'
export const NON_DEPLOYED_CONTRACT = 'NON_DEPLOYED_CONTRACT'

export const NO_USER_ACCOUNT = 'NO_USER_ACCOUNT'

// Transaction failures
export const FAILED_TO_PURCHASE_KEY = 'FAILED_TO_PURCHASE_KEY'

// Ticket failure
export const FAILED_TO_SIGN_ADDRESS = 'FAILED_TO_SIGN_ADDRESS'
