'use client'
import { useRouter } from 'next/navigation'

export const metadata = {
  title: 'Not Found',
  description: 'Generated by Next.js',
}

export default function NotFound({ children }: { children: React.ReactNode }) {
  const router = useRouter()

  router.replace('/404')
  return router.replace('/404')
}
