#!/usr/bin/env node

const ethers = require('ethers')
const args = require('yargs').argv

let provider = new ethers.providers.JsonRpcProvider(args.provider)
let value = args.value
let lockContractAddress = args.lockContractAddress
let erc20ContractAddress = args.erc20ContractAddress
let privateKey = args.privateKey

async function main() {
  let wallet = new ethers.Wallet(privateKey, provider)

  const contract = new ethers.Contract(
    erc20ContractAddress,
    ['function approve(address spender, uint256 value) returns (bool value)'],
    wallet
  )
  let result = await contract.approve(lockContractAddress, value)

  console.log(result)
}

main()
