name: Deployment
on: 
  push:
    branches:
      - master
      - production

jobs:
  # heroku deploys 
  deploy-locksmith-staging:    
    if: contains(github.base_ref, 'master')
    uses: unlock-protocol/unlock/.github/workflows/_heroku.yml@gh-actions
    with:
      service: locksmith
      app-name: unlock-locksmith-staging
  deploy-locksmith-production:    
    if: contains(github.base_ref, 'production')
    uses: unlock-protocol/unlock/.github/workflows/_heroku.yml@gh-actions
    with:
      service: locksmith
      app-name: unlock-locksmith-production

  deploy-locksmith-websub-staging:
    if: contains(github.base_ref, 'master')
    uses: unlock-protocol/unlock/.github/workflows/_heroku.yml@gh-actions
    with:
      service: locksmith-websub
      app-name: unlock-locksmith-websub-staging
  
  deploy-locksmith-websub-production:    
    if: contains(github.base_ref, 'production')
    uses: unlock-protocol/unlock/.github/workflows/_heroku.yml@gh-actions
    with:
      service: locksmith-websub
      app-name: unlock-locksmith-websub-production
  # netlify deploys
  deploy-unlock-app-netlify:
    uses: unlock-protocol/unlock/.github/workflows/_netlify.yml@gh-actions
    with:
      service: unlock-app
  deploy-paywall-to-netlify:
    uses: unlock-protocol/unlock/.github/workflows/_netlify.yml@gh-actions
    with:
      service: paywall-app
  deploy-newsletter-netlify:
    uses: unlock-protocol/unlock/.github/workflows/_netlify.yml@gh-actions
    with:
      service: "newsletter"
  deploy-unlock-protocol-com-netlify:
    uses: unlock-protocol/unlock/.github/workflows/_netlify.yml@gh-actions
    with:
      service: "unlock-protocol-com"
  
  # Fleek deloys
  deploy-paywall-to-fleek:
    uses: unlock-protocol/unlock/.github/workflows/_fleek.yml@gh-actions
    with:
      service: paywall-app
  deploy-unlock-app-fleek:
    uses: unlock-protocol/unlock/.github/workflows/_fleek.yml@gh-actions
    with:
      service: unlock-app
  deploy-newsletter-fleek:
    uses: unlock-protocol/unlock/.github/workflows/_fleek.yml@gh-actions
    with:
      service: "newsletter"
  deploy-unlock-protocol-com-fleek:
    uses: unlock-protocol/unlock/.github/workflows/_fleek.yml@gh-actions
    with:
      service: "unlock-protocol-com"