name: Fetch and Create Blog Posts
description: Fetches the latest blog posts from the Unlock Protocol blog and creates new posts in the website repository.
on:
  schedule:
    - cron: '0 0 * * *' # Run once per day at midnight
  pull_request:

jobs:
  fetch_and_create_posts:
    uses: ./.github/workflows/import-blog
