export { default as Web3Service } from './web3Service'
export { default as WalletService } from './walletService'
export { getCurrentProvider, getWeb3Provider } from './providers'
export const latestUnlock = 'v10'
export const latestPublicLock = 'v8'
