export { default as Web3Service } from './web3Service'
export { default as WalletService } from './walletService'
export { getCurrentProvider, getWeb3Provider } from './providers'
export const latestUnlock = 'v11'
export const latestPublicLock = 'v9'
export { LocksmithService } from './locksmithService'
