#!/bin/bash

read -r -d '' FILE << EOM
{
  "MAINNET_SUBGRAPH": "$MAINNET_SUBGRAPH",
  "OPTIMISM_SUBGRAPH": "$OPTIMISM_SUBGRAPH",
  "BSC_SUBGRAPH": "$BSC_SUBGRAPH",
  "GNOSIS_SUBGRAPH": "$GNOSIS_SUBGRAPH",
  "POLYGON_SUBGRAPH": "$POLYGON_SUBGRAPH",
  "ARBITRUM_SUBGRAPH": "$ARBITRUM_SUBGRAPH",
  "CELO_SUBGRAPH": "$CELO_SUBGRAPH",
  "AVALANCHE_SUBGRAPH": "$AVALANCHE_SUBGRAPH",
  "BASE_SUBGRAPH": "$BASE_SUBGRAPH",
  "BASE_SEPOLIA_SUBGRAPH": "$BASE_SEPOLIA_SUBGRAPH",
  "SEPOLIA_SUBGRAPH": "$SEPOLIA_SUBGRAPH",
  "LINEA_SUBGRAPH": "$LINEA_SUBGRAPH",
  "SCROLL_SUBGRAPH": "$SCROLL_SUBGRAPH",
  "ZKSYNC_SUBGRAPH": "$ZKSYNC_SUBGRAPH",
  "ZKEVM_SUBGRAPH": "$ZKEVM_SUBGRAPH"
} 
EOM

echo $FILE | yarn wrangler secret:bulk