name: Protocol Health Check
description: Check the state of the Unlock Protocol across all chains

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: yarn
      shell: bash
    - run: yarn build
      shell: bash
    - name: Run health checks
      run: |
        chmod +x ./scripts/health-check.sh
        ./scripts/health-check.sh
      shell: bash
