export const MISSING_PROVIDER = 'MISSING_PROVIDER'
export const MISSING_TRANSACTION = 'MISSING_TRANSACTION'
export const NOT_ENABLED_IN_PROVIDER = 'NOT_ENABLED_IN_PROVIDER'
export const NON_DEPLOYED_CONTRACT = 'NON_DEPLOYED_CONTRACT'

export const FORM_LOCK_NAME_MISSING = 'FORM_LOCK_NAME_MISSING'
export const FORM_EXPIRATION_DURATION_INVALID =
  'FORM_EXPIRATION_DURATION_INVALID'
export const FORM_MAX_KEYS_INVALID = 'FORM_MAX_KEYS_INVALID'
export const FORM_KEY_PRICE_INVALID = 'FORM_KEY_PRICE_INVALID'
