export const MISSING_PROVIDER = 'MISSING_PROVIDER'
export const MISSING_TRANSACTION = 'MISSING_TRANSACTION'
export const NOT_ENABLED_IN_PROVIDER = 'NOT_ENABLED_IN_PROVIDER'
export const NON_DEPLOYED_CONTRACT = 'NON_DEPLOYED_CONTRACT'
