name: Protocol Health Check

on:
  workflow_call:

jobs:
  health-check:
    name: Check the state of the Unlock Protocol for all chains
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      SENTRY_DSN: op://secrets/sentry-health-monitoring/credential
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: yarn build
      - name: Install Sentry CLI
        shell: bash
        run: npm install @sentry/cli -g
      - name: Check networks package
        run: |
          yarn workspace @unlock-protocol/networks check >> networks.log
          sentry-cli send-event -m "Networks" --logfile networks.log
        shell: bash
      - name: Check tokens in networks package
        run: |
          yarn workspace @unlock-protocol/networks check-tokens >> networks-tokens.log
          sentry-cli send-event -m "Networks Tokens" --logfile networks-tokens.log
        shell: bash
      - name: Check Unlock info
        run: |
          yarn workspace @unlock-protocol/governance check >> governance.log
          sentry-cli send-event -m "Governance" --logfile governance.log
      - name: Check Subgraphs
        run: |
          yarn workspace @unlock-protocol/subgraph check >> subgraph.log
          sentry-cli send-event -m "Subgraph" --logfile subgraph.log
      - name: Check Team Multisigs
        run: |
          yarn workspace @unlock-protocol/governance check:multisig >> multisig.log
          sentry-cli send-event -m "Multisig" --logfile multisig.log
        
