name: Run all tests

on:
  workflow_call:

jobs:
  run-all-tests:
    uses: ./.github/workflows/_tests.yml
    with:
      changed: '[
        "locksmith",
        "packages/unlock-js",
        "packages/paywall",
        "packages/contracts",
        "packages/hardhat-plugin",
        "smart-contracts",
        "smart-contract-extensions",
        "unlock-protocol-com",
        "wedlocks",
        "unlock-app"
        ]'