on: [pull_request]
name: Check changes in monorepo folders
jobs:
  check-changes:
    runs-on: ubuntu-latest
    name: "Check for changes in all monorepo"
    outputs:
      changed: ${{ steps.check-changes.outputs.changed }}
    env:
      TARGETS: '[
        "locksmith",
        "packages/unlock-js",
        "packages/paywall",
        "newsletter",
        "smart-contracts",
        "smart-contract-extensions",
        "unlock-protocol-com",
        "wedlocks",
        "unlock-app" 
        ]'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Check which folders have changed"
        run: |
          changed=$(.github/actions/monorepo/check-changes.sh)
          printf 'changed:%s\n' "${changed[@]}"
          echo ::set-output name=changed::'$changed'
        shell: bash
        id: check-changes
