name: "Daily checks"
on:
  schedule:
    # runs at 1am everyday
    - cron: '0 1 * * *'

jobs:
  health-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Load secrets from 1Password
        uses: 1Password/load-secrets-action@v1.3.2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SENTRY_AUTH_TOKEN: op://secrets/sentry-health-monitoring/credential
          SENTRY_DSN: op://secrets/sentry-health-monitoring/dsn      
      - name: Health Check of Unlock Protocol
        uses: ./.github/actions/health-check