name: "Heroku Deployments"

on:
  workflow_run:
    workflows: ["Unlock Test Suite"]
    types:
      - completed
    branches:
      - master
      - production

jobs:
  deploy-locksmith-staging:
    if: contains(github.base_ref, 'master')
    uses: ./.github/workflows/_heroku.yml
    with:
      service: locksmith
      app-name: unlock-locksmith-staging

  deploy-locksmith-production:
    if: contains(github.base_ref, 'production')
    uses: ./.github/workflows/_heroku.yml
    with:
      service: locksmith
      app-name: unlock-locksmith-production

  deploy-locksmith-websub-staging:
    if: contains(github.base_ref, 'master')
    uses: ./.github/workflows/_heroku.yml
    with:
      service: locksmith-websub
      build-dir: locksmith
      command: "yarn websub:prod"
      container-type: worker
      app-name: locksmith-websub-staging

  deploy-locksmith-websub-production:
    if: contains(github.base_ref, 'production')
    uses: ./.github/workflows/_heroku.yml
    with:
      service: locksmith-websub
      build-dir: locksmith
      command: "yarn websub:prod"
      container-type: worker
      app-name: locksmith-websub-production