name: Staging Deployment
on: 
  push:
    branches:
      - master
jobs:
  deploy-locksmith-staging:    
    uses: unlock-protocol/unlock/.github/workflows/heroku.yml@master
    with:
      service: locksmith
      app-name: unlock-locksmith-staging
