on:
  workflow_run:
    workflows: ["Unlock Test Suite"]
    types:
      - completed

name: Unlock Integration tests
jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
    steps:
      - uses: actions/checkout@v2
      - name: Run Integration Tests
        run: scripts/integration-tests.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: /tmp/screenshots
      - name: Log failing tests
        if: ${{ failure() }}
        run: ./scripts/docker-compose-log.sh