name: Deploy on Netlify

on:
  workflow_call:
    inputs:
      service:
        description: "The service/sub-repository to deploy"
        type: string
        required: true
      
jobs:
  deploy-to-netlify:
    name: Deploy ${{ input.service }} on Netlify
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
    steps:
      - uses: actions/checkout@v2
      - name: Check for changes in ${{ input.service }}
        run: |
          chmod +x ./scripts/monorepo.sh && \
          echo "::set-output name=${{ format('{0}_changed', input.service) }}::$(scripts/monorepo.sh ${{ input.service }} ${{ github.ref_name }})"
        shell: bash
        id: check_changes
      - name: Check if forked PR
        run: |
          echo "::set-output name=is_forked::$(${{github.repository_owner != 'Unlock Protocol' && github.event.pull_request.merged == true}})
      - name: Set target environment
        run: |
          echo "::set-output name=target::$(${{ github.ref == 'refs/heads/production' || input.service == 'unlock-protocol-com' }} && 'prod' || 'staging')"
      - name: Deploy to Netlify
        run: |
          chmod +x ./scripts/deploy.sh && \
          scripts/deploy.sh ${{ outputs.target }} ${{ input.service }} netlify "$GITHUB_SHA" "$GITHUB_REF_NAME" ${{ outputs.is_forked }}