on: [pull_request]
jobs:
  run-tests:
    name: Unlock Test Suite
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      BLOCKTIME: 0
    strategy:
      matrix:
        target: 
        - name: "unlock-js-tests"
          service: packages/unlock-js      
        - name: "paywall-lib-tests"
          service: packages/paywall      
        - name: "newsletter-tests"
          service: newsletter      
        - name: "smart-contracts-tests"
          service: smart-contracts      
        - name: "smart-contracts-extensions-tests"
          service: smart-contract-extensions      
        - name: "unlock-protocol-com-tests"
          service: unlock-protocol-com      
        - name: "wedlocks-tests"
          service: wedlocks      
        - name: "unlock-app-tests"
          service: unlock-app
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for changes in ${{ matrix.target.service }}
        run: |
          chmod +x ./scripts/monorepo.sh
          echo "::set-output name=${{ format('{0}_changed', matrix.target.name) }}::$(scripts/monorepo.sh ${{ matrix.target.service }} ${{ github.ref_name }})"
        shell: bash
        id: check_changes
      - name: Running ${{ matrix.target.service }} tests
        if: ${{ steps.check_changes.outputs[format('{0}_changed', matrix.target.name) ] == 'changed' }}
        run: |
          chmod +x ./scripts/tests.sh && \
          ./scripts/tests.sh ${{ matrix.target }}
        shell: bash