on: 
  workflow_run:
    workflows: [ "Check changes in monorepo" ]
    types: [completed]

name: Unlock Test Suite
jobs:
  monorepo-changes:
    runs-on: ubuntu-latest
    name: Get repos w changes
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Download artefact
        if: github.event_name == 'workflow_run'
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: 'Check changes in monorepo'
          workflow_conclusion: success
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
          run_number: ${{ github.event.workflow_run.run_number }}
          name: changed.json
      - id: set-matrix
        run: |
          JSON=$(cat changed.json)
          echo "::set-output name=matrix::${JSON//'%'/'%25'}"

  run-tests:
    needs: monorepo-changes
    name: Tests ${{ matrix.target }}
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      BLOCKTIME: 0
      # below env vars are just used by locksmith
      DB_USERNAME: locksmith_test
      DB_PASSWORD: password
      DB_NAME: locksmith_test
      DB_HOSTNAME: db
    strategy:
      matrix: 
        target: ${{fromJson(needs.monorepo-changes.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - name: Running ${{ matrix.target }} tests
        run: ./scripts/tests.sh ${{ matrix.target }}
        shell: bash