on: [pull_request]

name: Unlock Test Suite
jobs:
  monorepo-changes:
    runs-on: ubuntu-latest
    name: "Check for changes in all monorepo"
    outputs:
      changed: ${{ steps.check-changes.outputs.changed }}
    env:
      TARGETS: '[
        "locksmith",
        "packages/unlock-js",
        "packages/paywall",
        "newsletter",
        "smart-contracts",
        "smart-contract-extensions",
        "unlock-protocol-com",
        "wedlocks",
        "unlock-app" 
        ]'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Check which folders have changed"
        run: |
          changed=$(.github/actions/monorepo/check-changes.sh)
          printf 'changed:%s\n' "${changed[@]}"
          echo ::set-output name=changed::'$changed'
        shell: bash
        id: check-changes
    
  run-tests:
    needs: monorepo-changes
    name: Tests ${{ matrix.target }}
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      BLOCKTIME: 0
      # below env vars are just used by locksmith
      DB_USERNAME: locksmith_test
      DB_PASSWORD: password
      DB_NAME: locksmith_test
      DB_HOSTNAME: db
    strategy:
      matrix: 
        target: ${{fromJson(needs.monorepo-changes.outputs.changed)}}
    steps:
      - uses: actions/checkout@v2
      - name: Running ${{ matrix.target }} tests
        run: ./scripts/tests.sh ${{ matrix.target }}
        shell: bash