on: [pull_request]
jobs:
  run-tests:
    name: Unlock Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: 
        - packages/unlock-js
        - packages/paywall
        - newsletter
        - smart-contracts
        - smart-contract-extensions
        - unlock-protocol-com
        - wedlocks
        - unlock-app
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      BLOCKTIME: 0
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for changes in repository
        run: echo "::set-output name=${ matrix.target.service }_changed:$(scripts/monorepo.sh ${{ matrix.target.service }} ${{ github.ref_name }})"
        shell: bash
      - name: Running ${{ matrix.target.service }} tests
        if: ${{ matrix.target.service }}_changed
        run: scripts/tests.sh ${{ matrix.target.service }}
        shell: bash