export const POST_MESSAGE_LOCKED = 'locked'
export const POST_MESSAGE_UNLOCKED = 'unlocked'
export const POST_MESSAGE_SCROLL_POSITION = 'scrollPosition'
export const POST_MESSAGE_REDIRECT = 'redirect'
export const POST_MESSAGE_GET_OPTIMISTIC = 'optimistic'
export const POST_MESSAGE_GET_PESSIMISTIC = 'pessimistic'
