export const POST_MESSAGE_LOCKED = 'locked'
export const POST_MESSAGE_UNLOCKED = 'unlocked'
export const POST_MESSAGE_SCROLL_POSITION = 'scrollPosition'
export const POST_MESSAGE_REDIRECT = 'redirect'
export const POST_MESSAGE_GET_OPTIMISTIC = 'optimistic'
export const POST_MESSAGE_GET_PESSIMISTIC = 'pessimistic'
export const POST_MESSAGE_READY = 'ready'
export const POST_MESSAGE_CONFIG = 'config'
export const POST_MESSAGE_ACCOUNT = 'account'
export const POST_MESSAGE_WEB3 = 'web3'
export const POST_MESSAGE_WALLET_INFO = 'walletInfo'

export const POST_MESSAGE_DATA_REQUEST = 'data/request'
