export const POST_MESSAGE_LOCKED = 'locked'
export const POST_MESSAGE_UNLOCKED = 'unlocked'
export const POST_MESSAGE_SCROLL_POSITION = 'scrollPosition'
export const POST_MESSAGE_REDIRECT = 'redirect'
export const POST_MESSAGE_GET_OPTIMISTIC = 'optimistic'
export const POST_MESSAGE_GET_PESSIMISTIC = 'pessimistic'
export const POST_MESSAGE_READY = 'ready'
export const POST_MESSAGE_CONFIG = 'config'
export const POST_MESSAGE_ACCOUNT = 'account'
export const POST_MESSAGE_WEB3 = 'web3'
export const POST_MESSAGE_WALLET_INFO = 'walletInfo'

export const POST_MESSAGE_UPDATE_LOCKS = 'update/locks'
export const POST_MESSAGE_UPDATE_ACCOUNT = 'update/account'
export const POST_MESSAGE_UPDATE_ACCOUNT_BALANCE = 'update/accountBalance'
export const POST_MESSAGE_UPDATE_NETWORK = 'update/network'
export const POST_MESSAGE_UPDATE_WALLET = 'update/walletmodal'

export const POST_MESSAGE_ERROR = 'error'
export const POST_MESSAGE_SEND_UPDATES = 'semd/updates'

export const POST_MESSAGE_PURCHASE_KEY = 'purchaseKey'
